users_app/config/routes.rb
Rails.application.routes.draw do
 
  root 'users#index'
  resources :users do 
    post 'create_follow', on: :member
    post 'delete_follow', on: :member
    
  end
end

users_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

users_app/app/models/follow.rb
class Follow < ApplicationRecord
    
  belongs_to :follower, foreign_key: :follower_id, class_name: "User"

  belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"
end

users_app/app/models/user.rb
class User < ApplicationRecord

    has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow"

    has_many :followers, through: :received_follows, source: :follower

    has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
    
    has_many :followings, through: :given_follows, source: :followed_user

    def self.get_populars
    	User.all.sort_by{|u| u.followers.count}.last(3)
    end

    #Validation
    validates :username, presence: true
end

users_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user 

    def current_user
        @current_user ||= User.second
    end
end

users_app/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
end

users_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :edit, :destroy, :create_follow, :delete_follow]

  def index
    @users = User.all
    @following_count = @users
    .joins(:given_follows)
    .group('users.id')
    .count('follows.follower_id')
    @follower_count = @users
    .joins(:received_follows)
    .group('users.id')
    .count('follows.followed_user_id')

    @current_user_followings = current_user.followings.map(&:id)
  end

  def new 
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to @user #Deduce que tiene que ir al show del producto especifico
    else
      render :new, status: 422
    end
  end

  def create_follow
    Follow.create(follower_id: @current_user.id, followed_user_id: @user.id)
    render turbo_stream: 
      turbo_stream.replace('index', partial: @user)
    #redirect_to users_path
  end

  def delete_follow
    delete_follow = Follow.find_by(follower_id: @current_user.id, followed_user_id: @user.id)
    delete_follow.delete
    #redirect_to users_path
  end

  def show
    @follower_count = []
    @follower_count[@user.id] = @user.followers.count
    
    @following_count = []
    @following_count[@user.id] = @user.followings.count

    @current_user_followings = current_user.followings.map(&:id)
  end

  def edit; end

  def update
    if @user.update(user_params)  
      redirect_to @user #Deduce que tiene que ir al show del producto especifico
    else
      render :edit, status: 422
    end
  end

  def destroy
    @user.destroy!
    redirect_to users_path
  end

  private

  def set_user #Me ahorra tener que buscar el usuario en cada metodo
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

users_app/app/helpers/application_helper.rb
module ApplicationHelper
end

users_app/app/helpers/follows_helper.rb
module FollowsHelper
end

users_app/app/helpers/users_helper.rb
module UsersHelper
end

users_app/app/views/follows/index.html.erb
<h1>Follows#index</h1>
<p>Find me in app/views/follows/index.html.erb</p>

users_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    Current user id: <%= @current_user.id %>
    Current user username: <%= @current_user.username %>
    <%= yield %>

    <%= turbo_frame_tag 'modal' %>
  </body>
</html>

users_app/app/views/users/_form.html.erb
<%= form_with model: @user do |u| %>

  <%= u.label :username %>
  <%= u.text_field :username %>

  <%= u.submit %>
<% end %>

users_app/app/views/users/_user.html.erb
<turbo-frame id="<%= dom_id(user) %>">

	<tr>
		<td> <%= user.id %> </td>
		<td><%= user.username%> </td>
		<td> <%= follower_count[user.id] || 0 %> </td>
		<td> <%= following_count[user.id] || 0 %> </td>
		<td style='display:flex; gap:20px'><%= link_to 'See', user_path(user.id)%>
		<%= link_to 'Edit', edit_user_path(user.id)%>
		
		<% if @current_user != user %>
			<%= button_to 'DELETE', user_path(user.id), method: :delete, form: { data: { turbo_confirm: "Are you sure?" }}%>
		<% end %>

		<% if @current_user != user %>
			<% if @current_user_followings.include?(user.id)%>
				<%= button_to 'Unfollow', delete_follow_user_path(user.id), method: :post, :style=>'color: red;'%></td>
			<% else %>
				<%= button_to 'Follow', create_follow_user_path(user.id), method: :post, :style=>'color: green;' %>
			<% end %>
		<% end %>
	</tr>
</turbo-frame>

users_app/app/views/users/edit.html.erb
<h1>User edit</h1>
<h2><%= @user.errors.full_messages if @user.errors.full_messages.any?%></h2>
<%= render"form", user: @user %>
<%= link_to 'Home', users_path %>

users_app/app/views/users/index.html.erb
<h1>Users Home</h1>
<h1> La cantidad de usuarios es: <%= @users.count %> </h2>
<%= link_to 'Crear nuevo usuario', new_user_path %>
<%= @current_user_followings%>
<table style='width:40%; text-align:center'>

  <thead>
    <th>
      ID
    </th>
    <th>
    Nombre
    </th>
    <th>
    Seguidores
    </th>
    <th>
    Seguidos
    </th>
    <th>
    </th>
  </thead>

<tbody>
  <%= turbo_frame_tag 'index' do %>
      <%= render @users,
      follower_count: @follower_count,
      following_count: @following_count %>
  <% end %>
</tbody>

</table>

users_app/app/views/users/new.html.erb
    <h1>User new</h1>
    <h2><%= @user.errors.full_messages if @user.errors.full_messages.any?%></h2>
    <%= render"form", user: @user %>
    <%= link_to 'Home', users_path %>
    

users_app/app/views/users/show.html.erb
<table style='width:60%; text-align:center'>

  <thead>
    <th>
      ID
    </th>
    <th>
    Nombre
    </th>
    <th>
    Seguidores
    </th>
    <th>
    Seguidos
    </th>
    <th>
    </th>
  </thead>

<tbody>
  <tr>
    <h1>User Details</h1>
    <%= render @user,
      follower_count: @follower_count,
      following_count: @following_count %>
    <%= link_to 'Home', users_path %>
  </tr>

</tbody>

</table>

users_app/app/views/users/user.turbo_stream.erb
<turbo-stream action='replace' target= "<%= dom_id(@user) %>">
  <template>
    <%= render @user %>
  <template>
<turbo-stream>